### ISSUE TITLE
Syntax errors in table_creation.sql

### ISSUE THREAD

**Issue by rfkay3** [rfkay3/hobi#1]
I am getting 7 syntax errors around the User identifier. Is "User" a reserved keyword in our DBMS?

**Comment by harrislr** [comment]
I’d imagine. I had to change the name of group to groupinfo because I was getting errors. I was using an online ide thing to test the code since I was in the lab so it’s possible it used a different version or something.

**Comment by harrislr** [comment]
Also why are we communicating through GitHub

**Comment by rfkay3** [comment]
Better to do it on here and be able to look back if we have problems down the road/do code review and can't remember why we did something.

**Comment by harrislr** [comment]
I guess 😒

**Comment by harrislr** [comment]
We should be good now, I changed User to UserLogin
